[run]
source = app/
omit = 
    # Exclusion du dossier model
    app/ml/model/
    # Exclusion des fichiers __init__
    app/**/__init__.py
    # Exclusion de fichiers connus (importé ailleurs et donc déjà testé)
    app/**/save_load_datas.py