[pytest]
# Chemin des tests se trouve dans le dossier tests/
testpaths = tests
# Les fichiers de tests commencent par test_
python_files = test_*.py
# Seuls les fonctions commencant par test_ = test
python_functions = test_*
# Seuls les classes commencant par Test = test
python_classes = Test*
# Ajoute le répertoire courant au PYTHONPATH
pythonpath = .
env_files = .env.test
# active pytest asynchrone
asyncio_mode = auto
# Comportement CLI
log_cli = true
log_cli_level = INFO

#==========================
# LES COMMENTAIRES INLINE NE SONT PAS AUTORISES DANS LE FICHIER pytest.ini
#==========================
# v Verbose
# strict-markers interdit l'utilisation de marqueurs non définis
# tb=short traceback court
# cov=app.ml.model Mesure couverture du code dans app/ml/model.py
# cov=app.api Mesure couverture du code dans app/api/schemas.py
# cov-report=term-missing Affiche les files/lignes non couvertes dans le terminal
# cov-report=html Génère un rapport HTML
# cov-fail-under=80 Echec si la couverture n'est pas de 80%
addopts = 
    -v
    --strict-markers
    --tb=short
    --cov=app
    --cov=CLI
    --cov-config=coverage.ini
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=80

# Markers pour eviter de tout tester si besoin (fonctionne avec @pytest.mark.)
markers =
    unit: Tests unitaires rapides et isolés.
    integration: Tests vérifiant interaction entre composants.
    functional: Tests de bout en bout - RAG complet, API.